import Head from "next/head";
import ApartCard from "../components/ApartCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MyRiverPlace Apartments | Porto</title>
        <meta
          name="description"
          content="Generated by create next app CHANGE CHANGE CHANGE CHANGE"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="main-image"></div>
        <ApartCard />
      </main>
    </div>
  );
}
