import Head from "next/head";
import ApartCard from "../components/ApartCard";
import TourCard from "../components/TourCard";

export default function Home() {
  return (
    <div>
      <Head>
        <title>MyRiverPlace Apartments | Porto</title>
        <meta
          name="description"
          content="Generated by create next app CHANGE CHANGE CHANGE CHANGE"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div className="main-image"></div>
        <div className="apart-col">
          <ApartCard />
          <ApartCard />
        </div>
        <div className="tour-col">
          <div className="tour-sect-title">
            <i className="bi bi-signpost-2-fill"></i> Tours
          </div>
          <TourCard />
        </div>
      </main>
    </div>
  );
}
